=== MaxwellJalves/trabalhandoComXml/out/production/trabalhandoComXml/com/estruturaXml/schemas/pedido/pedidoDeCompra.xsd
<?xml version="1.0" encoding="UTF-8"?>
<apelido:schema xmlns:apelido="http://www.w3.org/2001/XMLSchema">
    <apelido:element name="pedidoDeCompra">
        <apelido:complexType>
            <apelido:sequence>
                <apelido:element name="header">
                    <apelido:complexType>
                        <apelido:sequence>
                            <apelido:element name="identificador" type="apelido:integer"/>
                            <apelido:element name="codigoLojaParceira" type="apelido:integer"/>
                            <apelido:element name="codigoDoCliente" type="apelido:integer"/>
                        </apelido:sequence>
                    </apelido:complexType>
                </apelido:element>
                <apelido:element name="body">
                    <apelido:complexType>
                        <apelido:sequence>
                            <apelido:element name="pedidos">
                                <apelido:complexType>
                                    <apelido:sequence>
                                        <apelido:element name="produto" maxOccurs="unbounded">
                                            <apelido:complexType>
                                                <apelido:sequence>
                                                    <apelido:element name="codigo" type="apelido:int"/>
                                                    <apelido:element name="nome" type="apelido:string"/>
                                                    <apelido:element name="valor" type="apelido:double"/>
                                                    <apelido:element name="quantidade" type="apelido:double"/>
                                                </apelido:sequence>
                                            </apelido:complexType>
                                        </apelido:element>
                                    </apelido:sequence>
                                </apelido:complexType>
                            </apelido:element>
                            <apelido:element name="dadosDoCliente" maxOccurs="unbounded">
                                <apelido:complexType>
                                    <apelido:sequence>
                                        <apelido:element  name="nome"     type="apelido:string"/>
                                        <apelido:element  name="endereco" type="apelido:string"/>
                                        <apelido:element  name="numero"   type="apelido:int"/>
                                        <apelido:element  name="bairro"   type="apelido:string"/>
                                    </apelido:sequence>
                                </apelido:complexType>
                            </apelido:element>
                        </apelido:sequence>
                    </apelido:complexType>
                </apelido:element>
            </apelido:sequence>
        </apelido:complexType>
    </apelido:element>

</apelido:schema>

=== MaxwellJalves/trabalhandoComXml/src/com/estruturaXml/schemas/pedido/pedidoDeCompra.xml
<?xml version="1.0" encoding="UTF-8" ?>
<pedidoDeCompra xsi:noNamespaceSchemaLocation="pedidoDeCompra.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
        <identificador>1</identificador>
        <codigoLojaParceira>10</codigoLojaParceira>
        <codigoDoCliente>1020</codigoDoCliente>
    </header>
    <body>
     <pedidos>
         <produto>
             <codigo>05545215</codigo>
             <nome>COCA COLA</nome>
             <valor>5.20</valor>
             <quantidade>2</quantidade>
         </produto>
         <produto>
             <codigo>2323</codigo>
             <nome>PIZZA DO DIA</nome>
             <valor>25.90</valor>
             <quantidade>2</quantidade>
         </produto>
         <produto>
             <codigo>9999</codigo>
             <nome>COMBO KIDS</nome>
             <valor>22.90</valor>
             <quantidade>1</quantidade>
         </produto>
     </pedidos>
     <dadosDoCliente>
         <nome>MAXWELL</nome>
         <endereco>Rua B</endereco>
         <numero>12</numero>
         <bairro>CENTRO</bairro>
     </dadosDoCliente>
    </body>
</pedidoDeCompra>
