=== MaxwellJalves/trabalhandoComXml/out/production/trabalhandoComXml/com/estruturaXml/schemas/modulo/otica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <element name="pontoDeVenda">
      <complexType>
          <sequence>
              <element name="funcionario" type="string"/>
              <element name="horaAberturaCaixa" type="date"/>
              <element name="turno" type="string"/>
              <element name="vlFundCaixa" type="decimal"/>
              <element name = "listaDeProdutos">
                  <complexType>
                      <sequence>
                          <element name="produto">
                              <complexType>
                                  <sequence>
                                      <element name="item" type="int"/>
                                      <element name="descricao" type="string"/>
                                      <element name="valor" type="double"/>
                                      <element name="observacao" type="string"/>
                                  </sequence>
                              </complexType>
                          </element>
                      </sequence>
                  </complexType>
              </element>
          </sequence>
      </complexType>
    </element>


</schema>

=== MaxwellJalves/trabalhandoComXml/out/production/trabalhandoComXml/com/estruturaXml/schemas/modulo/otica.xml
<?xml version="1.0" encoding="UTF-8"  ?>
    <pontoDeVenda xsi:noNamespaceSchemaLocation="otica.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >OTICA_RECIFE
        <funcionario>MAXWELL</funcionario>
        <horaAberturaCaixa>08:00</horaAberturaCaixa>
        <turno>MANHÃ</turno>
        <vlFundoCaixa>450.00</vlFundoCaixa>
        <listaDeProdutos>
            <produto>
                <item>100</item>
                <descricao>Oculos de Sol </descricao>
                <valor>20000</valor>
                <observacao> ta barato</observacao>
            </produto>
            <produto>
                <item>101</item>
                <descricao>Oculos Quadrado Maculino</descricao>
                <valor>870</valor>
                <observacao> made in Brasil</observacao>
            </produto>
            <produto>
                <item>999</item>
                <descricao>Oculos Resto de Estoque Promoção TOP</descricao>
                <valor>10</valor>
                <observacao> NÃO DEVOLVEMOS MERCADORIAS, AGREÇO A PREFERENCIA!</observacao>
            </produto>
        </listaDeProdutos>
    </pontoDeVenda>
